openapi: "3.0.0"
info:
  title: GoOutSafe user microservice
  version: "0.0.1"
paths:
  /get:
    get:
      operationId: user_microservice.views.user.get
      responses:
        "200":
          description: "returns a count"
          content:
            text/plain:
              schema:
                type: integer
